# -*- coding: utf-8 -*-
"""villadelrey_b7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkHSLaKYFc0tJnCP2tENughjg1FyTid_
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam_Table.csv', skip_blank_lines=True).dropna()

output = df.transpose()

output.to_csv('./drive/MyDrive/b7_output.csv')