# -*- coding: utf-8 -*-
"""villadelrey_b1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1ZTOeLLOmc3DvQZbKmKK4OscAK_HumP
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam_Table.csv')

output = df[df['Interval']=='30-0']

output.to_csv("./drive/My Drive/b1_output.csv", index=False)