# -*- coding: utf-8 -*-
"""villadelrey_b4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183Ak6HcFWyqz7rDndjsSvvcLn9EWu0TF
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam_Table.csv', skip_blank_lines=True).dropna()

sciname = df["Scientific Name"].unique()

ave = df.groupby("Scientific Name")["Size Est (cm)"].mean()

output = pd.DataFrame({"Scientific Name": sciname, "Averages": ave})

output.to_csv("./drive/My Drive/b4_output.csv")