# -*- coding: utf-8 -*-
"""villadelrey_b5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddV5xDTgn9d90QyzEQyumsdQ8w3uHUcN
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam_Table.csv', skip_blank_lines=True).dropna()

ave = df.groupby("Scientific Name")["Size Est (cm)"].mean()

output = pd.DataFrame({"Scientific Name": ["Pomacentrus adelus"], "Average count": ave["Pomacentrus adelus"]})

output.to_csv('./drive/My Drive/b5_output.csv')