# -*- coding: utf-8 -*-
"""villadelrey_b6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLi6eJhOupQ3cShGnM7ii8MSFB63WICh
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam_Table.csv', skip_blank_lines=True).dropna()

output = df["HRID"] = df["Location"].apply(lambda x: x.replace(",","-").replace(" ","")) +"-"+ df["Site"] +"-"+ df["Replicate"].astype(int).astype(str)

output.to_csv('./drive/My Drive/b6_output.csv')