# -*- coding: utf-8 -*-
"""villadelrey_b2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSuynswoSpc_xMo2CPv40c-iJ1Urb1_z
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam_Table.csv', skip_blank_lines=True).dropna()

output = df[df['Genus'].str.match('st', case=False)]

output.to_csv("./drive/My Drive/b2_output.csv")