# -*- coding: utf-8 -*-
"""villadelrey_b3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4Y-UqZJQDSGI56rBcBhzbNUVbuNBB0R
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam_Table.csv')

output = df['Scientific Name'].drop_duplicates().dropna()

output.to_csv("./drive/My Drive/b3_output.csv")